### ISSUE TITLE
GitHub Actions での Rspec が MySQL への接続の影響で失敗する問題

### ISSUE THREAD

**Issue by myosotis-dev** [TKYcraft/mahirun#24]
## 概要
Actions の Rspec が安定しない, コケる場合がある
https://github.com/TKYcraft/mahirun/actions/runs/5705449048/attempts/3

## 原因
- `compose.yaml` で定義しているMySQL コンテナへの接続が失敗することがある

## 追加の背景情報
- healthcheck は 以下のcommitにて強めに掛け直しているので、それ以外に問題がありそう
	- c42d12111cca8cd9dfc66f06b2bece1b1523c6dd
	- (GitHub Actionsがコンテナで動いているのでcomposeのネットワークが不安定な可能性)

## メモ
- compose.rspec.yaml の MySQL コンテナについて [replicas](https://docs.docker.jp/compose/compose-file/deploy.html#replicas) を0にすることで起動しないことができるかチェックすること。

**Comment by Alicey0719** [comment]
composeじゃなくてActions側でMySQLを定義したほがよさげ？

**Comment by myosotis-dev** [comment]
考えらられる方法は3種類 (今後取りうる方法は下2つ)
- compose.yaml で MySQL コンテナを定義する方法 (現状、コレで駄目な可能性が高い)
- workflow.yaml で service に MySQL コンテナを定義する方法
- GitHub Action の Ubuntu ホストランナーには MySQL が pre-installed なのでコレを使う。

**Comment by Alicey0719** [comment]
3は、どうやってネットワーク的な疎通とるんや？

**Comment by myosotis-dev** [comment]
あまりきれいな方法を思いつかない。無理やりやるなら Docker Network をHost mode にするとかいう強硬手段を取ることになると思う。

**Comment by Alicey0719** [comment]
compose使わずにmysqlのイメージ起動するのが良さそうな気がしている
